# Generated by Django 5.2.4 on 2025-08-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner', models.CharField(max_length=255)),
                ('respondent', models.CharField(max_length=255)),
                ('filing_date', models.CharField(blank=True, max_length=100, null=True)),
                ('next_hearing_date', models.CharField(blank=True, max_length=100, null=True)),
                ('judgment_pdf_url', models.URLField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.courtquery')),
            ],
        ),
    ]
